-- fleet-auth schema v1: api_keys + api_key_role_assignment.
--
-- Belt-and-suspenders CHECK constraints catch row-level invariants
-- (prefix format, hash format, revoke/active coherence, expiry sanity)
-- at the database boundary in addition to the application-level
-- validation in `validation.rs`. See ADR-0030 for the broader design.

CREATE TABLE api_keys (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix      TEXT        NOT NULL,
    name        TEXT        NOT NULL,
    hash        TEXT        NOT NULL,
    kind        TEXT        NOT NULL CHECK (kind IN ('human', 'service')),
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ,
    last_used   TIMESTAMPTZ,
    revoked_at  TIMESTAMPTZ,

    CONSTRAINT api_keys_prefix_format
        CHECK (prefix ~ '^[A-Za-z0-9_-]{8}$'),
    CONSTRAINT api_keys_name_nonempty
        CHECK (length(name) > 0),
    CONSTRAINT api_keys_hash_argon2id
        CHECK (hash LIKE '$argon2id$%'),
    CONSTRAINT api_keys_revoked_inactive
        CHECK (revoked_at IS NULL OR active = FALSE),
    CONSTRAINT api_keys_expiry_after_create
        CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE UNIQUE INDEX api_keys_prefix_idx ON api_keys (prefix);

-- Partial index over active keys, descending by creation time — the
-- list_keys(active_only=true) admin path. Tiny at fleet scale; cheap.
CREATE INDEX api_keys_active_created_idx
    ON api_keys (created_at DESC)
    WHERE active;

CREATE TABLE api_key_role_assignment (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id  BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    app     TEXT   NOT NULL,
    role    TEXT   NOT NULL,

    CONSTRAINT api_key_role_assignment_unique_app
        UNIQUE (key_id, app),
    CONSTRAINT api_key_role_assignment_app_format
        CHECK (app ~ '^[a-z0-9_]{1,64}$'),
    CONSTRAINT api_key_role_assignment_role_nonempty
        CHECK (length(role) BETWEEN 1 AND 128),
    CONSTRAINT api_key_role_assignment_role_no_control_chars
        CHECK (role !~ '[[:cntrl:]]')
);

CREATE INDEX api_key_role_assignment_key_idx
    ON api_key_role_assignment (key_id);
