-- Initial Fleet keystore schema. Requires a fresh dedicated database.
-- Append forward migrations; do not edit an applied baseline.
-- Keys and roles are operator-created. The registry grants no permissions.

CREATE TABLE api_keys (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix      TEXT        NOT NULL,
    name        TEXT        NOT NULL,
    hash        TEXT        NOT NULL,
    kind        TEXT        NOT NULL CHECK (kind IN ('human', 'service')),
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ,
    last_used   TIMESTAMPTZ,
    revoked_at  TIMESTAMPTZ,

    CONSTRAINT api_keys_prefix_format
        CHECK (prefix ~ '^[A-Za-z0-9_-]{8}$'),
    CONSTRAINT api_keys_name_nonempty
        CHECK (length(name) > 0),
    CONSTRAINT api_keys_hash_argon2id
        CHECK (hash LIKE '$argon2id$%'),
    CONSTRAINT api_keys_revoked_inactive
        CHECK (revoked_at IS NULL OR active = FALSE),
    CONSTRAINT api_keys_expiry_after_create
        CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE UNIQUE INDEX api_keys_prefix_idx ON api_keys (prefix);

-- Partial index over active keys, descending by creation time — the
-- list_keys(active_only=true) admin path. Tiny at fleet scale; cheap.
CREATE INDEX api_keys_active_created_idx
    ON api_keys (created_at DESC)
    WHERE active;

CREATE TABLE roles (
    id        BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT    NOT NULL,
    -- Nullable per-role rate ceiling (requests/minute). When any of a
    -- key's roles set it, the key's effective RPM is the MAX across its
    -- roles and OVERRIDES the route-class config default (ADR-0006
    -- "Slice 0 design decisions"). CHECK > 0: an override can never be 0,
    -- so "0 disables limiting" remains a config-default-only semantic.
    rate_rpm  INTEGER,

    CONSTRAINT roles_name_format
        CHECK (name ~ '^[a-z0-9_-]{1,64}$'),
    CONSTRAINT roles_rate_rpm_positive
        CHECK (rate_rpm IS NULL OR rate_rpm > 0)
);

CREATE UNIQUE INDEX roles_name_idx ON roles (name);

CREATE TABLE role_permissions (
    role_id     BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    app         TEXT   NOT NULL,
    permission  TEXT   NOT NULL,

    PRIMARY KEY (role_id, app, permission),
    CONSTRAINT role_permissions_app_format
        CHECK (app ~ '^[a-z0-9_]{1,64}$'),
    CONSTRAINT role_permissions_permission_format
        CHECK (permission ~ '^[a-z0-9_]{1,64}$')
);

CREATE TABLE key_roles (
    key_id   BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    -- No ON DELETE CASCADE: deleting a role that keys still hold must be
    -- an explicit, forced act (AuthError::RoleInUse), never a silent
    -- capability strip.
    role_id  BIGINT NOT NULL REFERENCES roles(id),

    PRIMARY KEY (key_id, role_id)
);

CREATE INDEX key_roles_role_idx ON key_roles (role_id);

-- Warn-only permission vocabulary registry: fleet-admin warns when a role
-- mutation names a permission absent from here, but persists it anyway (a
-- role may pre-name a permission an app is about to ship).
CREATE TABLE app_permissions (
    app         TEXT NOT NULL,
    permission  TEXT NOT NULL,

    PRIMARY KEY (app, permission),
    CONSTRAINT app_permissions_app_format
        CHECK (app ~ '^[a-z0-9_]{1,64}$'),
    CONSTRAINT app_permissions_permission_format
        CHECK (permission ~ '^[a-z0-9_]{1,64}$')
);

-- Warn-only vocabulary. No default roles, keys, grants, or memberships.
INSERT INTO app_permissions (app, permission) VALUES
    ('trawl', 'query'),
    ('trawl', 'schema_read'),
    ('trawl', 'validate'),
    ('trawl', 'saved_query'),
    ('trawl', 'export'),
    ('trawl', 'stream'),
    ('trawl', 'query_cancel'),
    ('trawl', 'server_manage'),
    ('trawl', 'ingest'),
    ('trawl', 'schema_write');
