-- fleet-auth schema v2: roles-as-data RBAC (ADR-0006 slice 1).
--
-- Replaces the static (key, app, role) grant model with data-defined
-- roles: a role is a named, cross-app bundle of permission strings; keys
-- hold any number of roles; effective permissions are the union.
--
-- The same migration converts legacy grants in place — one role per
-- distinct legacy (app, role) pair, named `<app>-<role>` — seeds the
-- permission lists both apps hardcode today as static strings (trawl's
-- from policy.rs minus the dead `key_manage`; coastwatch's from its
-- `permissions_for`, snake_case of the variant names), links keys via
-- key_roles, and DROPs api_key_role_assignment. Irreversible by design,
-- consistent with repo migration doctrine.

CREATE TABLE roles (
    id        BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT    NOT NULL,
    -- Nullable per-role rate ceiling (requests/minute). When any of a
    -- key's roles set it, the key's effective RPM is the MAX across its
    -- roles and OVERRIDES the route-class config default (ADR-0006
    -- "Slice 0 design decisions"). CHECK > 0: an override can never be 0,
    -- so "0 disables limiting" remains a config-default-only semantic.
    rate_rpm  INTEGER,

    CONSTRAINT roles_name_format
        CHECK (name ~ '^[a-z0-9_-]{1,64}$'),
    CONSTRAINT roles_rate_rpm_positive
        CHECK (rate_rpm IS NULL OR rate_rpm > 0)
);

CREATE UNIQUE INDEX roles_name_idx ON roles (name);

CREATE TABLE role_permissions (
    role_id     BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    app         TEXT   NOT NULL,
    permission  TEXT   NOT NULL,

    PRIMARY KEY (role_id, app, permission),
    CONSTRAINT role_permissions_app_format
        CHECK (app ~ '^[a-z0-9_]{1,64}$'),
    CONSTRAINT role_permissions_permission_format
        CHECK (permission ~ '^[a-z0-9_]{1,64}$')
);

CREATE TABLE key_roles (
    key_id   BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    -- No ON DELETE CASCADE: deleting a role that keys still hold must be
    -- an explicit, forced act (AuthError::RoleInUse), never a silent
    -- capability strip.
    role_id  BIGINT NOT NULL REFERENCES roles(id),

    PRIMARY KEY (key_id, role_id)
);

CREATE INDEX key_roles_role_idx ON key_roles (role_id);

-- Warn-only permission vocabulary registry: fleet-admin warns when a role
-- mutation names a permission absent from here, but persists it anyway (a
-- role may pre-name a permission an app is about to ship).
CREATE TABLE app_permissions (
    app         TEXT NOT NULL,
    permission  TEXT NOT NULL,

    PRIMARY KEY (app, permission),
    CONSTRAINT app_permissions_app_format
        CHECK (app ~ '^[a-z0-9_]{1,64}$'),
    CONSTRAINT app_permissions_permission_format
        CHECK (permission ~ '^[a-z0-9_]{1,64}$')
);

-- ---------------------------------------------------------------------------
-- In-place conversion of legacy grants (no re-minting; live keys work
-- through the deploy).
-- ---------------------------------------------------------------------------

-- Pre-flight: v1 allowed far looser role strings than `roles_name_format`
-- (any 1..=128 bytes without control chars, any case), and even a legal
-- lowercase role can overflow 64 bytes once `<app>-` is prepended. Name
-- the offending grants instead of aborting on an opaque CHECK violation —
-- the operator fixes them in `api_key_role_assignment` (still present at
-- this point) and re-runs the migration.
DO $$
DECLARE
    offenders TEXT;
BEGIN
    SELECT string_agg(format('(app=%L, role=%L)', app, role), ', ' ORDER BY app, role)
    INTO offenders
    FROM (SELECT DISTINCT app, role FROM api_key_role_assignment) g
    WHERE (g.app || '-' || g.role) !~ '^[a-z0-9_-]{1,64}$';

    IF offenders IS NOT NULL THEN
        RAISE EXCEPTION
            'roles-as-data conversion: legacy grants whose <app>-<role> name is not a valid role name: %',
            offenders
            USING ERRCODE = 'check_violation',
                  HINT = 'A converted role name must match ^[a-z0-9_-]{1,64}$ (note the <app>- prefix counts toward the 64 bytes). Rename these roles in api_key_role_assignment (UPDATE api_key_role_assignment SET role = ''<new>'' WHERE app = ''<app>'' AND role = ''<old>'') and re-run the migration.';
    END IF;
END
$$;

-- One role per distinct legacy (app, role) pair, named `<app>-<role>`.
INSERT INTO roles (name)
SELECT DISTINCT app || '-' || role
FROM api_key_role_assignment;

-- Freeze trawl's compile-time role → permission tables (policy.rs) as data.
-- `key_manage` is intentionally dropped: no handler or route ever checked
-- it (the variant dies in the same PR).
INSERT INTO role_permissions (role_id, app, permission)
SELECT r.id, 'trawl', p.permission
FROM roles r
CROSS JOIN (VALUES
    ('query'), ('schema_read'), ('validate'), ('saved_query'),
    ('export'), ('stream'), ('query_cancel'), ('server_manage')
) AS p(permission)
WHERE r.name = 'trawl-admin';

INSERT INTO role_permissions (role_id, app, permission)
SELECT r.id, 'trawl', p.permission
FROM roles r
CROSS JOIN (VALUES
    ('query'), ('schema_read'), ('validate'), ('saved_query'),
    ('export'), ('stream'), ('query_cancel')
) AS p(permission)
WHERE r.name = 'trawl-analyst';

INSERT INTO role_permissions (role_id, app, permission)
SELECT r.id, 'trawl', p.permission
FROM roles r
CROSS JOIN (VALUES
    ('query'), ('schema_read'), ('query_cancel')
) AS p(permission)
WHERE r.name = 'trawl-reader';

INSERT INTO role_permissions (role_id, app, permission)
SELECT r.id, 'trawl', 'ingest'
FROM roles r
WHERE r.name = 'trawl-ingest';

-- Freeze coastwatch's compile-time `permissions_for` table as data. Wire
-- strings are snake_case of the variant names — the convention ADR-0006
-- itself uses (e.g. `coastwatch:stories_read`). Coastwatch's companion arc
-- owes an `as_str` matching these exact strings (see the cutover runbook).
INSERT INTO role_permissions (role_id, app, permission)
SELECT r.id, 'coastwatch', p.permission
FROM roles r
CROSS JOIN (VALUES
    ('stories_read'), ('analyst_decisions_write'), ('editions_review'),
    ('editions_revise'), ('editions_correct'), ('ioc_exports_read'),
    ('pipeline_read'), ('document_upload')
) AS p(permission)
WHERE r.name = 'coastwatch-analyst';

INSERT INTO role_permissions (role_id, app, permission)
SELECT r.id, 'coastwatch', p.permission
FROM roles r
CROSS JOIN (VALUES
    ('system_config_manage'), ('api_keys_manage'), ('editions_revise'),
    ('pipeline_read'), ('document_upload')
) AS p(permission)
WHERE r.name = 'coastwatch-operator';

INSERT INTO role_permissions (role_id, app, permission)
SELECT r.id, 'coastwatch', 'ioc_exports_read'
FROM roles r
WHERE r.name = 'coastwatch-siem_consumer';

-- Link every key to the converted role for each of its legacy grants.
INSERT INTO key_roles (key_id, role_id)
SELECT a.key_id, r.id
FROM api_key_role_assignment a
JOIN roles r ON r.name = a.app || '-' || a.role;

-- Seed trawl's live permission vocabulary (the 9 strings handlers check;
-- `key_manage` is never seeded — the variant dies). Coastwatch seeds its
-- own vocabulary in its companion arc; the registry is warn-only, so the
-- gap is cosmetic until then.
INSERT INTO app_permissions (app, permission) VALUES
    ('trawl', 'query'),
    ('trawl', 'schema_read'),
    ('trawl', 'validate'),
    ('trawl', 'saved_query'),
    ('trawl', 'export'),
    ('trawl', 'stream'),
    ('trawl', 'query_cancel'),
    ('trawl', 'server_manage'),
    ('trawl', 'ingest');

DROP TABLE api_key_role_assignment;
