// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! `design-cards` — emit static HTML preview cards from fleet-ui's
//! class contracts, for iteration on claude.ai/design.
//!
//! fleet-ui components are wasm32-gated CSR, so there is no native
//! render-to-string: each snippet emitter below mirrors the markup its
//! leptos counterpart renders (the `view!` blocks under
//! `crates/fleet-ui/src/`). When a component's DOM changes, the emitter
//! here must change with it — the cards are DERIVED artifacts,
//! regenerated by `cargo xtask design-cards`, never hand-edited.
//!
//! Each card is one self-contained HTML file: `@dsCard` marker on line
//! one, `fleet-ui.css` inlined, and the same snippet stamped into a
//! light pane and a dark pane side by side. The theme split works
//! because fleet-ui.css scopes all color tokens under bare
//! `[data-theme=…]` attribute selectors — re-declaring the attribute on
//! a `<section>` re-scopes every token beneath it. Gallery-only chrome
//! uses a `ds-` class prefix so it can never collide with fleet
//! selectors.

// The whole module builds HTML by mapping snippet emitters over slices;
// the fold+write! shape clippy prefers buries the templates in plumbing.
#![allow(clippy::format_collect)]

use std::fs;
use std::path::Path;
use std::process::ExitCode;

/// Google Fonts links, same families/weights as the consuming apps
/// (`crates/trawl-web-ui/index.html`) — fleet-ui.css declares the
/// families but deliberately does not load them.
const FONT_LINKS: &str = r#"<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap"/>"#;

/// Gallery scaffolding: the light/dark split, section headings, swatch
/// grid, and neutralizers for fleet's fixed-position overlay/toast
/// hosts so they render inline inside a pane.
const GALLERY_CSS: &str = r"
body { margin: 0; font-family: var(--font-ui); }
.ds-split { display: grid; grid-template-columns: 1fr 1fr; min-height: 100vh; }
.ds-pane { background: var(--bg); color: var(--ink); padding: 20px 24px; }
.ds-pane h2 {
  font-size: 11px; font-weight: 600; text-transform: uppercase;
  letter-spacing: .08em; color: var(--ink-3);
  margin: 22px 0 10px; padding-bottom: 4px;
  border-bottom: 1px solid var(--line);
}
.ds-pane h2:first-child { margin-top: 0; }
.ds-row { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-bottom: 10px; }
.ds-col { display: flex; flex-direction: column; gap: 12px; max-width: 340px; }
.ds-label { font-size: 11px; color: var(--ink-3); min-width: 72px; }
.ds-swatches { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; }
.ds-swatch { border: 1px solid var(--line); border-radius: 6px; overflow: hidden; }
.ds-swatch .chip { height: 44px; }
.ds-swatch .name {
  font-family: var(--font-mono); font-size: 10px; color: var(--ink-2);
  padding: 4px 6px; background: var(--panel);
}
.ds-type { margin: 0 0 8px; color: var(--ink); }
.ds-shadowbox {
  width: 120px; height: 56px; border-radius: 8px;
  background: var(--panel); border: 1px solid var(--line);
  display: flex; align-items: center; justify-content: center;
  font-size: 10px; font-family: var(--font-mono); color: var(--ink-3);
}
.ds-spacebar { background: var(--amber-wash); border: 1px solid var(--amber); height: 14px; }
/* Fleet's overlay/toast hosts are position:fixed full-viewport; pin
 * them into the pane flow so both themes show in one card. */
.ds-pane .modal-scrim { position: static; padding: 24px 0; }
.ds-pane .toasts { position: static; padding: 0; }
";

struct Card {
    slug: &'static str,
    group: &'static str,
    title: &'static str,
    body: String,
}

/// Generate all cards into `out_dir`. `css_path` is the canonical
/// fleet-ui stylesheet (`crates/fleet-ui/styles/fleet-ui.css`).
pub fn generate(css_path: &Path, out_dir: &Path) -> ExitCode {
    let css = match fs::read_to_string(css_path) {
        Ok(css) => css,
        Err(e) => {
            eprintln!("xtask: failed to read {}: {e}", css_path.display());
            return ExitCode::FAILURE;
        }
    };
    if let Err(e) = fs::create_dir_all(out_dir) {
        eprintln!("xtask: failed to create {}: {e}", out_dir.display());
        return ExitCode::FAILURE;
    }

    let cards = [
        tokens_card(),
        actions_card(),
        feedback_card(),
        forms_card(),
        overlays_card(),
    ];

    for card in &cards {
        let path = out_dir.join(format!("{}.html", card.slug));
        let html = render_card(card, &css);
        if let Err(e) = fs::write(&path, html) {
            eprintln!("xtask: failed to write {}: {e}", path.display());
            return ExitCode::FAILURE;
        }
        eprintln!("xtask: wrote {}", path.display());
    }
    ExitCode::SUCCESS
}

/// Wrap a card body in the full HTML shell: `@dsCard` marker first
/// line, inlined fleet CSS, then the same body stamped into a light
/// pane and a dark pane.
fn render_card(card: &Card, fleet_css: &str) -> String {
    format!(
        r#"<!-- @dsCard group="{group}" -->
<!doctype html>
<html data-theme="light">
<head>
<meta charset="utf-8"/>
<title>{title} — fleet-ui</title>
{FONT_LINKS}
<style>
{fleet_css}
</style>
<style>
{GALLERY_CSS}
</style>
</head>
<body>
<div class="ds-split">
<section class="ds-pane" data-theme="light">
{body}
</section>
<section class="ds-pane" data-theme="dark">
{body}
</section>
</div>
</body>
</html>
"#,
        group = card.group,
        title = card.title,
        body = card.body,
    )
}

// ── snippet emitters — each mirrors a fleet-ui component's view! ────

/// `<Btn/>` — `crates/fleet-ui/src/button/`: `btn_class(variant, size,
/// full)` composes `.btn-pri`/`.btn-sec`/`.btn-danger`/`.btn`, with
/// `.btn-sm` standalone, `.btn-xs` composing, `.btn-full` appended.
fn btn(class: &str, label: &str, disabled: bool) -> String {
    let dis = if disabled { " disabled" } else { "" };
    format!(r#"<button class="{class}"{dis}>{label}</button>"#)
}

/// `<Badge/>` — `badge_class(tone)` = `bdg {{tone}}`.
fn badge(tone: &str, label: &str) -> String {
    format!(r#"<span class="bdg {tone}">{label}</span>"#)
}

/// `<StatusDot/>` — `dot_class(tone)`; Neutral renders the bare class.
fn status_dot(tone: &str) -> String {
    if tone.is_empty() {
        r#"<span class="status-dot"></span>"#.to_string()
    } else {
        format!(r#"<span class="status-dot {tone}"></span>"#)
    }
}

/// `<IconView/>` — 16×16 viewBox, currentColor stroke (icon.rs).
fn icon_svg(size: u8, body: &str) -> String {
    format!(
        r#"<svg width="{size}" height="{size}" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">{body}</svg>"#
    )
}

fn search_icon() -> String {
    icon_svg(
        12,
        r#"<g><circle cx="7" cy="7" r="4.5"/><path d="m10.5 10.5 3 3"/></g>"#,
    )
}

fn close_icon() -> String {
    icon_svg(12, r#"<g><path d="m4 4 8 8M12 4l-8 8"/></g>"#)
}

/// `<Field/>` default shape — `.field > label + control + helper`.
fn field(id: &str, label: &str, control: &str, helper: Option<(&str, &str)>) -> String {
    let helper_html = helper.map_or(String::new(), |(class, text)| {
        format!(r#"<p id="{id}-help" class="{class}">{text}</p>"#)
    });
    format!(r#"<div class="field"><label for="{id}">{label}</label>{control}{helper_html}</div>"#)
}

/// `<SearchInput/>` — `.inp-wrap` with the search glyph.
fn search_input(placeholder: &str) -> String {
    format!(
        r#"<div class="inp-wrap">{icon}<input placeholder="{placeholder}"/></div>"#,
        icon = search_icon()
    )
}

/// `<Toggle/>` — `.toggle > input[type=checkbox] + .toggle-slider`.
fn toggle(checked: bool) -> String {
    let chk = if checked { " checked" } else { "" };
    format!(
        r#"<label class="toggle"><input type="checkbox"{chk}/><span class="toggle-slider"></span></label>"#
    )
}

/// `<Segmented/>` — `segmented_class(size, full)` over `.seg-opt[.on]`.
fn segmented(class: &str, options: &[&str], active: usize) -> String {
    let opts: String = options
        .iter()
        .enumerate()
        .map(|(i, label)| {
            let on = if i == active { " on" } else { "" };
            format!(r#"<button class="seg-opt{on}">{label}</button>"#)
        })
        .collect();
    format!(r#"<div class="{class}">{opts}</div>"#)
}

/// `<Modal/>` shell in static open state — `modal/shell.rs`.
fn modal(narrow: bool, title: &str, body: &str, footer: &str) -> String {
    let panel_class = if narrow { "modal modal-sm" } else { "modal" };
    format!(
        r#"<div class="modal-scrim">
  <div class="{panel_class}" role="dialog" aria-modal="true">
    <div class="m-hd">
      <span class="t">{title}</span>
      <span class="x" title="Close (Esc)">{close}</span>
    </div>
    <div class="m-body">{body}</div>
    <div class="m-ft">{footer}</div>
  </div>
</div>"#,
        close = close_icon()
    )
}

fn labeled_row(label: &str, content: &str) -> String {
    format!(r#"<div class="ds-row"><span class="ds-label">{label}</span>{content}</div>"#)
}

fn heading(text: &str) -> String {
    format!("<h2>{text}</h2>")
}

// ── the five cards ──────────────────────────────────────────────────

fn tokens_card() -> Card {
    let surface_tokens = ["--bg", "--panel", "--panel-2", "--panel-3"];
    let ink_tokens = ["--ink", "--ink-2", "--ink-3", "--ink-4"];
    let line_tokens = ["--line", "--line-2", "--selection", "--amber-glow"];
    let semantic_tokens = [
        "--amber",
        "--teal",
        "--red",
        "--yellow",
        "--green",
        "--blue",
        "--amber-wash",
        "--red-wash",
    ];

    let swatch_grid = |tokens: &[&str]| -> String {
        let swatches: String = tokens
            .iter()
            .map(|t| {
                format!(
                    r#"<div class="ds-swatch"><div class="chip" style="background:var({t})"></div><div class="name">{t}</div></div>"#
                )
            })
            .collect();
        format!(r#"<div class="ds-swatches">{swatches}</div>"#)
    };

    let type_specimens = r#"
<p class="ds-type" style="font-size:16px; font-weight:600">Heading — Inter 600 / 16px</p>
<p class="ds-type" style="font-size:13px">Body — Inter 400 / 13px</p>
<p class="ds-type" style="font-size:11px; color:var(--ink-3)">Caption — Inter 400 / 11px</p>
<p class="ds-type" style="font-family:var(--font-mono); font-size:var(--editor-fs)">Editor mono — JetBrains Mono / var(--editor-fs)</p>
<p class="ds-type" style="font-family:var(--font-mono); font-size:var(--table-fs)">Table mono — JetBrains Mono / var(--table-fs)</p>"#;

    let spacing_bars: String = ["--row-pad-y", "--row-pad-x", "--ui-gap", "--pad", "--row-h"]
        .iter()
        .map(|t| {
            labeled_row(
                t,
                &format!(r#"<div class="ds-spacebar" style="width:calc(var({t}) * 4)"></div>"#),
            )
        })
        .collect();

    let shadows: String = ["--shadow-1", "--shadow-2", "--shadow-3", "--shadow-glow"]
        .iter()
        .map(|t| format!(r#"<div class="ds-shadowbox" style="box-shadow:var({t})">{t}</div>"#))
        .collect();

    let body = format!(
        "{h_surfaces}{surfaces}{h_inks}{inks}{h_lines}{lines}{h_semantic}{semantic}\
         {h_type}{type_specimens}{h_spacing}{spacing_bars}{h_shadows}\
         <div class=\"ds-row\">{shadows}</div>",
        h_surfaces = heading("Surfaces"),
        surfaces = swatch_grid(&surface_tokens),
        h_inks = heading("Inks"),
        inks = swatch_grid(&ink_tokens),
        h_lines = heading("Lines & selection"),
        lines = swatch_grid(&line_tokens),
        h_semantic = heading("Semantic"),
        semantic = swatch_grid(&semantic_tokens),
        h_type = heading("Type scale"),
        h_spacing = heading("Spacing (4×)"),
        h_shadows = heading("Shadows"),
    );

    Card {
        slug: "tokens",
        group: "Foundations",
        title: "Tokens",
        body,
    }
}

fn actions_card() -> Card {
    let variants = [
        ("Primary", "btn-pri"),
        ("Secondary", "btn-sec"),
        ("Danger", "btn-danger"),
        ("Form", "btn"),
    ];

    let default_row: String = variants
        .iter()
        .map(|(label, class)| btn(class, label, false))
        .collect::<String>();
    let xs_row: String = variants
        .iter()
        .map(|(label, class)| btn(&format!("{class} btn-xs"), label, false))
        .collect::<String>();
    let disabled_row: String = variants
        .iter()
        .map(|(label, class)| btn(class, label, true))
        .collect::<String>();

    let body = format!(
        "{h_btn}{r_default}{r_sm}{r_xs}{r_disabled}{r_full}{h_kbd}{r_kbd}{h_seg}{r_seg}{r_seg_sm}",
        h_btn = heading("Btn — variant × size"),
        r_default = labeled_row("default", &default_row),
        r_sm = labeled_row("sm", &btn("btn-sm", "Small", false)),
        r_xs = labeled_row("xs", &xs_row),
        r_disabled = labeled_row("disabled", &disabled_row),
        r_full = labeled_row(
            "full",
            &format!(
                r#"<div style="width:260px">{}</div>"#,
                btn("btn-pri btn-full", "Full width", false)
            )
        ),
        h_kbd = heading("Kbd"),
        r_kbd = labeled_row(
            "chips",
            r#"<span class="kbd">⌘⏎</span><span class="kbd">Esc</span><span class="kbd-inline">⌘K</span>"#
        ),
        h_seg = heading("Segmented"),
        r_seg = labeled_row("default", &segmented("seg", &["CSV", "JSON", "Parquet"], 0)),
        r_seg_sm = labeled_row("sm", &segmented("seg seg-sm", &["1h", "24h", "7d"], 1)),
    );

    Card {
        slug: "actions",
        group: "Actions",
        title: "Actions",
        body,
    }
}

fn feedback_card() -> Card {
    let badges: String = [
        ("neutral", "Neutral"),
        ("info", "Info"),
        ("success", "Success"),
        ("warn", "Warn"),
        ("danger", "Danger"),
    ]
    .iter()
    .map(|(tone, label)| badge(tone, label))
    .collect::<String>();

    let dots: String = [("", "neutral"), ("success", "success"), ("error", "error"), ("running", "running")]
        .iter()
        .map(|(tone, label)| {
            format!(
                r#"<span style="display:inline-flex; align-items:center; gap:6px; font-size:12px">{dot}{label}</span>"#,
                dot = status_dot(tone)
            )
        })
        .collect::<String>();

    let toast = |kind: &str, title: &str, detail: &str| {
        format!(
            r#"<div class="toast {kind}"><div class="body"><div class="title">{title}</div><div class="detail">{detail}</div></div><span class="x">{close}</span></div>"#,
            close = close_icon()
        )
    };

    let body = format!(
        "{h_badge}{r_badge}{h_dot}{r_dot}{h_err}{banner}{h_hint}{hint}{h_toast}<div class=\"toasts\">{t1}{t2}{t3}</div>",
        h_badge = heading("Badge — tones"),
        r_badge = labeled_row("tones", &badges),
        h_dot = heading("StatusDot"),
        r_dot = labeled_row("tones", &dots),
        h_err = heading("ErrorBanner"),
        banner =
            r#"<div class="error" role="alert">couldn't reach trawld: connection refused</div>"#,
        h_hint = heading("Loaded — load hints"),
        hint = r#"<div class="load-hint">Loading history…</div><div class="load-hint error">couldn't load history</div>"#,
        h_toast = heading("Toasts"),
        t1 = toast("success", "Saved", "Query \"errors by host\" saved"),
        t2 = toast("error", "Copy failed", "Clipboard unavailable"),
        t3 = toast("info", "Schedule updated", "Next run in 2 hours"),
    );

    Card {
        slug: "feedback",
        group: "Feedback",
        title: "Feedback",
        body,
    }
}

fn forms_card() -> Card {
    let toggles = format!("{}{}", toggle(true), toggle(false));
    let seg_full = format!(
        r#"<div style="max-width:340px">{}</div>"#,
        segmented("seg seg-full", &["CSV", "JSON", "Parquet"], 2)
    );
    let body = format!(
        "{h_field}<div class=\"ds-col\">{f_hint}{f_error}</div>{h_search}{r_search}{h_toggle}{r_toggle}{h_seg}{r_seg}",
        h_field = heading("Field"),
        f_hint = field(
            "name",
            "Query name",
            r#"<input type="text" id="name" value="errors by host"/>"#,
            Some(("field-hint", "Shown in the saved-queries list.")),
        ),
        f_error = field(
            "token",
            "API token",
            r#"<input type="password" id="token" value="hunter2"/>"#,
            Some(("error", "Token was rejected by the server.")),
        ),
        h_search = heading("SearchInput"),
        r_search = labeled_row("filter", &search_input("Filter runs…")),
        h_toggle = heading("Toggle"),
        r_toggle = labeled_row("states", &toggles),
        h_seg = heading("Segmented — full width"),
        r_seg = seg_full,
    );

    Card {
        slug: "forms",
        group: "Forms",
        title: "Forms",
        body,
    }
}

fn overlays_card() -> Card {
    let export_modal = modal(
        false,
        "Export results",
        &format!(
            r#"<div class="m-field"><label>Format</label>{seg}</div><div class="m-field"><label>File name</label><input type="text" value="report.csv"/></div>"#,
            seg = segmented("seg seg-full", &["CSV", "JSON", "Parquet"], 0)
        ),
        &format!(
            "<div></div>{cancel}{confirm}",
            cancel = btn("btn-sec", "Cancel", false),
            confirm = btn("btn-pri", "Export", false)
        ),
    );

    let confirm_modal = modal(
        true,
        "Delete saved query",
        r#"<p style="margin:0; font-size:13px; color:var(--ink-2)">Delete "errors by host"? This can't be undone.</p>"#,
        &format!(
            "<div></div>{cancel}{del}",
            cancel = btn("btn-sec", "Cancel", false),
            del = btn("btn-danger", "Delete", false)
        ),
    );

    let body = format!(
        "{h_modal}{export_modal}{h_confirm}{confirm_modal}",
        h_modal = heading("Modal"),
        h_confirm = heading("ConfirmModal (narrow, alertdialog)"),
    );

    Card {
        slug: "overlays",
        group: "Overlays",
        title: "Overlays",
        body,
    }
}
