// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! `design-cards` — emit static HTML preview cards from fleet-ui's
//! class contracts, for iteration on claude.ai/design.
//!
//! fleet-ui components are wasm32-gated CSR, so there is no native
//! render-to-string: each snippet emitter below mirrors the markup its
//! leptos counterpart renders (the `view!` blocks under
//! `crates/fleet-ui/src/`). When a component's DOM changes, the emitter
//! here must change with it — the cards are derived artifacts,
//! regenerated by `cargo xtask design-cards`, never hand-edited.
//!
//! Each card is one self-contained HTML file: `@dsCard` marker on line
//! one, `fleet-ui.css` inlined, and the same snippet stamped into a
//! light pane and a dark pane side by side. The theme split works
//! because fleet-ui.css scopes all color tokens under bare
//! `[data-theme=…]` attribute selectors — re-declaring the attribute on
//! a `<section>` re-scopes every token beneath it. Gallery-only chrome
//! uses a `ds-` class prefix so it can never collide with fleet
//! selectors.

// The whole module builds HTML by mapping snippet emitters over slices;
// the fold+write! shape clippy prefers buries the templates in plumbing.
#![allow(clippy::format_collect)]

use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::process::ExitCode;

use base64ct::{Base64, Encoding as _};
use fleet_ui::badge::{Tone, badge_class};
use fleet_ui::button::{Size, Variant, btn_class};
use fleet_ui::segmented::segmented_class;
use fleet_ui::sparkline::spark_path;
use fleet_ui::status_dot::{StatusTone, dot_class};

/// Gallery scaffolding: the light/dark split, section headings, swatch
/// grid, and neutralizers for fleet's fixed-position overlay/toast
/// hosts so they render inline inside a pane.
const GALLERY_CSS: &str = r"
body { margin: 0; font-family: var(--font-ui); }
.ds-split { display: grid; grid-template-columns: 1fr 1fr; min-height: 100vh; }
.ds-pane { background: var(--bg); color: var(--ink); padding: 20px 24px; }
.ds-pane h2 {
  font-size: 11px; font-weight: 600; text-transform: uppercase;
  letter-spacing: .08em; color: var(--ink-3);
  margin: 22px 0 10px; padding-bottom: 4px;
  border-bottom: 1px solid var(--line);
}
.ds-pane h2:first-child { margin-top: 0; }
.ds-row { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-bottom: 10px; }
.ds-col { display: flex; flex-direction: column; gap: 12px; max-width: 340px; }
.ds-label { font-size: 11px; color: var(--ink-3); min-width: 72px; }
.ds-swatches { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; }
.ds-swatch { border: 1px solid var(--line); border-radius: 6px; overflow: hidden; }
.ds-swatch .chip { height: 44px; }
.ds-swatch .name {
  font-family: var(--font-mono); font-size: 10px; color: var(--ink-2);
  padding: 4px 6px; background: var(--panel);
}
.ds-type { margin: 0 0 8px; color: var(--ink); }
.ds-shadowbox {
  width: 120px; height: 56px; border-radius: 8px;
  background: var(--panel); border: 1px solid var(--line);
  display: flex; align-items: center; justify-content: center;
  font-size: 10px; font-family: var(--font-mono); color: var(--ink-3);
}
.ds-spacebar { background: var(--accent-wash); border: 1px solid var(--accent); height: 14px; }
/* Fleet's overlay/toast/drawer hosts are position:fixed full-viewport;
 * pin them into the pane flow so both themes show in one card. */
.ds-pane .modal-scrim { position: static; padding: 24px 0; }
.ds-pane .toasts { position: static; padding: 0; }
.ds-pane .sd-scrim { position: static; padding: 16px 0; background: rgba(20,15,5,.06); }
.ds-pane .sd-drawer { position: static; width: 100%; height: 380px; box-shadow: var(--shadow-3); }
.ds-pane .login-shell { height: auto; padding: 24px 0; }
/* Room for absolutely-positioned dropdowns rendered in open state; the
 * left margin keeps the right-anchored .actions-menu inside the pane. */
.ds-dropdown-room { min-height: 170px; }
.ds-dropdown-room .actions-wrap { margin-left: 160px; }
/* Wide-chrome cards stack light above dark instead of side by side. */
.ds-split.ds-stacked { grid-template-columns: 1fr; }
";

struct Card {
    slug: &'static str,
    group: &'static str,
    title: &'static str,
    body: String,
    /// Stack the theme panes vertically (for wide chrome like `TopBar`
    /// that can't fit in a half-width pane).
    stacked: bool,
}

/// Generate all cards into `out_dir`. `css_path` is the canonical
/// fleet-ui stylesheet and `fonts_dir` its committed self-hosted assets.
pub fn generate(css_path: &Path, fonts_dir: &Path, out_dir: &Path) -> ExitCode {
    let assets = fs::read_to_string(css_path)
        .and_then(|css| inline_fonts(css, fonts_dir))
        .and_then(|css| {
            fs::read_to_string(fonts_dir.join("OFL.txt")).map(|license| (css, license))
        });
    let (css, font_license) = match assets {
        Ok(assets) => assets,
        Err(e) => {
            eprintln!("xtask: failed to load design assets: {e}");
            return ExitCode::FAILURE;
        }
    };
    if let Err(e) = fs::create_dir_all(out_dir) {
        eprintln!("xtask: failed to create {}: {e}", out_dir.display());
        return ExitCode::FAILURE;
    }
    let cards = [
        tokens_card(),
        actions_card(),
        feedback_card(),
        forms_card(),
        overlays_card(),
        navigation_card(),
        data_card(),
        drawer_card(),
        reason_modal_card(),
        login_card(),
        chrome_card(),
    ];

    for card in &cards {
        let path = out_dir.join(format!("{}.html", card.slug));
        let html = render_card(card, &css, &font_license);
        if let Err(e) = fs::write(&path, html) {
            eprintln!("xtask: failed to write {}: {e}", path.display());
            return ExitCode::FAILURE;
        }
        eprintln!("xtask: wrote {}", path.display());
    }
    ExitCode::SUCCESS
}

/// Keep each generated card self-contained by replacing the canonical
/// stylesheet's dist-relative font URLs with data URLs sourced from the exact
/// committed fleet-ui files. The Trunk consumers copy those same files.
fn inline_fonts(mut css: String, fonts_dir: &Path) -> std::io::Result<String> {
    for name in ["Geist-Variable.woff2", "GeistMono-Variable.woff2"] {
        let bytes = fs::read(fonts_dir.join(name))?;
        let relative = format!("fonts/{name}");
        if !css.contains(&relative) {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("fleet-ui.css has no `{relative}` font URL"),
            ));
        }
        let data_url = format!("data:font/woff2;base64,{}", Base64::encode_string(&bytes));
        css = css.replace(&relative, &data_url);
    }
    Ok(css)
}

/// Wrap a card body in the full HTML shell: `@dsCard` marker first
/// line, inlined fleet CSS, then the same body stamped into a light
/// pane and a dark pane.
fn render_card(card: &Card, fleet_css: &str, font_license: &str) -> String {
    format!(
        r#"<!-- @dsCard group="{group}" -->
<!doctype html>
<html data-theme="light">
<head>
<meta charset="utf-8"/>
<title>{title} — fleet-ui</title>
<script type="text/plain" id="geist-font-license">
{font_license}
</script>
<style>
{fleet_css}
</style>
<style>
{GALLERY_CSS}
</style>
</head>
<body>
<div class="ds-split{stacked}">
<section class="ds-pane" data-theme="light">
{body}
</section>
<section class="ds-pane" data-theme="dark">
{body}
</section>
</div>
</body>
</html>
"#,
        group = card.group,
        title = card.title,
        body = card.body,
        font_license = font_license,
        stacked = if card.stacked { " ds-stacked" } else { "" },
    )
}

// ── snippet emitters — each mirrors a fleet-ui component's view! ────

/// `<Btn/>` — class composition via fleet-ui's own `btn_class`, so the
/// gallery can't drift from `crates/fleet-ui/src/button/variant.rs`.
fn btn(variant: Variant, size: Size, label: &str, disabled: bool) -> String {
    btn_full(variant, size, false, label, disabled)
}

fn btn_full(variant: Variant, size: Size, full: bool, label: &str, disabled: bool) -> String {
    let class = btn_class(variant, size, full);
    let dis = if disabled { " disabled" } else { "" };
    format!(r#"<button class="{class}"{dis}>{label}</button>"#)
}

/// `<Badge/>` — class via fleet-ui's `badge_class`.
fn badge(tone: Tone, label: &str) -> String {
    let class = badge_class(tone);
    format!(r#"<span class="{class}">{label}</span>"#)
}

/// `<StatusDot/>` — class via fleet-ui's `dot_class`.
fn status_dot(tone: StatusTone) -> String {
    let class = dot_class(tone);
    format!(r#"<span class="{class}"></span>"#)
}

/// `<IconView/>` — 16×16 viewBox, currentColor stroke (icon.rs).
fn icon_svg(size: u8, body: &str) -> String {
    format!(
        r#"<svg width="{size}" height="{size}" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">{body}</svg>"#
    )
}

fn search_icon() -> String {
    icon_svg(
        12,
        r#"<g><circle cx="7" cy="7" r="4.5"/><path d="m10.5 10.5 3 3"/></g>"#,
    )
}

fn close_icon() -> String {
    icon_svg(12, r#"<g><path d="m4 4 8 8M12 4l-8 8"/></g>"#)
}

/// `<Field/>` default shape — `.field > label + control + helper`.
fn field(id: &str, label: &str, control: &str, helper: Option<(&str, &str)>) -> String {
    let helper_html = helper.map_or(String::new(), |(class, text)| {
        format!(r#"<p id="{id}-help" class="{class}">{text}</p>"#)
    });
    format!(r#"<div class="field"><label for="{id}">{label}</label>{control}{helper_html}</div>"#)
}

/// `<SearchInput/>` — `.inp-wrap` with the search glyph.
fn search_input(placeholder: &str) -> String {
    format!(
        r#"<div class="inp-wrap">{icon}<input placeholder="{placeholder}"/></div>"#,
        icon = search_icon()
    )
}

/// `<Toggle/>` — `.toggle > input[type=checkbox] + .toggle-slider`.
fn toggle(checked: bool) -> String {
    let chk = if checked { " checked" } else { "" };
    format!(
        r#"<label class="toggle"><input type="checkbox"{chk}/><span class="toggle-slider"></span></label>"#
    )
}

/// `<Segmented/>` — class via fleet-ui's `segmented_class` over
/// `.seg-opt[.on]` option buttons.
fn segmented(size: Size, full: bool, options: &[&str], active: usize) -> String {
    let class = segmented_class(size, full);
    let opts: String = options
        .iter()
        .enumerate()
        .map(|(i, label)| {
            let on = if i == active { " on" } else { "" };
            format!(r#"<button class="seg-opt{on}">{label}</button>"#)
        })
        .collect();
    format!(r#"<div class="{class}">{opts}</div>"#)
}

/// `<Modal/>` shell in static open state — `modal/shell.rs`.
fn modal(narrow: bool, title: &str, body: &str, footer: &str) -> String {
    let panel_class = if narrow { "modal modal-sm" } else { "modal" };
    format!(
        r#"<div class="modal-scrim">
  <div class="{panel_class}" role="dialog" aria-modal="true">
    <div class="m-hd">
      <span class="t">{title}</span>
      <span class="x" title="Close (Esc)">{close}</span>
    </div>
    <div class="m-body">{body}</div>
    <div class="m-ft">{footer}</div>
  </div>
</div>"#,
        close = close_icon()
    )
}

fn labeled_row(label: &str, content: &str) -> String {
    format!(r#"<div class="ds-row"><span class="ds-label">{label}</span>{content}</div>"#)
}

fn heading(text: &str) -> String {
    format!("<h2>{text}</h2>")
}

// ── cards ───────────────────────────────────────────────────────────

fn tokens_card() -> Card {
    let surface_tokens = ["--bg", "--panel", "--panel-2", "--panel-3"];
    let ink_tokens = ["--ink", "--ink-2", "--ink-3", "--ink-4"];
    let line_tokens = ["--line", "--line-2", "--selection", "--accent-glow"];
    let semantic_tokens = [
        "--accent",
        "--teal",
        "--red",
        "--yellow",
        "--green",
        "--blue",
        "--accent-wash",
        "--red-wash",
    ];

    let swatch_grid = |tokens: &[&str]| -> String {
        let swatches: String = tokens
            .iter()
            .map(|t| {
                format!(
                    r#"<div class="ds-swatch"><div class="chip" style="background:var({t})"></div><div class="name">{t}</div></div>"#
                )
            })
            .collect();
        format!(r#"<div class="ds-swatches">{swatches}</div>"#)
    };

    let type_specimens = r#"
<p class="ds-type" style="font-size:var(--fs-title); font-weight:600">Title — Geist 600 / var(--fs-title)</p>
<p class="ds-type" style="font-size:var(--fs-section); font-weight:600">Section — Geist 600 / var(--fs-section)</p>
<p class="ds-type" style="font-size:var(--fs-base)">Body — Geist 400 / var(--fs-base)</p>
<p class="ds-type" style="font-size:var(--fs-control)">Control — Geist 400 / var(--fs-control)</p>
<p class="ds-type" style="font-size:var(--fs-label)">Label — Geist 400 / var(--fs-label)</p>
<p class="ds-type" style="font-size:var(--fs-small); color:var(--ink-3)">Small — Geist 400 / var(--fs-small)</p>
<p class="ds-type" style="font-family:var(--font-mono); font-size:var(--editor-fs)">Editor mono — Geist Mono / var(--editor-fs)</p>
<p class="ds-type" style="font-family:var(--font-mono); font-size:var(--table-fs)">Table mono — Geist Mono / var(--table-fs)</p>"#;

    let spacing_bars: String = ["--row-pad-y", "--row-pad-x", "--ui-gap", "--pad", "--row-h"]
        .iter()
        .map(|t| {
            labeled_row(
                t,
                &format!(r#"<div class="ds-spacebar" style="width:calc(var({t}) * 4)"></div>"#),
            )
        })
        .collect();

    let shadows: String = ["--shadow-1", "--shadow-2", "--shadow-3", "--shadow-glow"]
        .iter()
        .map(|t| format!(r#"<div class="ds-shadowbox" style="box-shadow:var({t})">{t}</div>"#))
        .collect();

    let body = format!(
        "{h_surfaces}{surfaces}{h_inks}{inks}{h_lines}{lines}{h_semantic}{semantic}\
         {h_type}{type_specimens}{h_spacing}{spacing_bars}{h_shadows}\
         <div class=\"ds-row\">{shadows}</div>",
        h_surfaces = heading("Surfaces"),
        surfaces = swatch_grid(&surface_tokens),
        h_inks = heading("Inks"),
        inks = swatch_grid(&ink_tokens),
        h_lines = heading("Lines & selection"),
        lines = swatch_grid(&line_tokens),
        h_semantic = heading("Semantic"),
        semantic = swatch_grid(&semantic_tokens),
        h_type = heading("Type scale"),
        h_spacing = heading("Spacing (4×)"),
        h_shadows = heading("Shadows"),
    );

    Card {
        slug: "tokens",
        group: "Foundations",
        title: "Tokens",
        body,
        stacked: false,
    }
}

fn actions_card() -> Card {
    let variants = [
        ("Primary", Variant::Primary),
        ("Secondary", Variant::Secondary),
        ("Danger", Variant::Danger),
        ("Form", Variant::Form),
    ];

    let default_row: String = variants
        .iter()
        .map(|(label, v)| btn(*v, Size::Default, label, false))
        .collect::<String>();
    let xs_row: String = variants
        .iter()
        .map(|(label, v)| btn(*v, Size::Xs, label, false))
        .collect::<String>();
    let disabled_row: String = variants
        .iter()
        .map(|(label, v)| btn(*v, Size::Default, label, true))
        .collect::<String>();
    let full_btn = format!(
        r#"<div style="width:260px">{}</div>"#,
        btn_full(Variant::Primary, Size::Default, true, "Full width", false)
    );

    let body = format!(
        "{h_btn}{r_default}{r_sm}{r_xs}{r_disabled}{r_full}{h_kbd}{r_kbd}{h_seg}{r_seg}{r_seg_sm}",
        h_btn = heading("Btn — variant × size"),
        r_default = labeled_row("default", &default_row),
        r_sm = labeled_row("sm", &btn(Variant::Secondary, Size::Sm, "Small", false)),
        r_xs = labeled_row("xs", &xs_row),
        r_disabled = labeled_row("disabled", &disabled_row),
        r_full = labeled_row("full", &full_btn),
        h_kbd = heading("Kbd"),
        r_kbd = labeled_row(
            "chips",
            r#"<span class="kbd">⌘⏎</span><span class="kbd">Esc</span><span class="kbd-inline">⌘K</span>"#
        ),
        h_seg = heading("Segmented"),
        r_seg = labeled_row(
            "default",
            &segmented(Size::Default, false, &["CSV", "JSON", "Parquet"], 0)
        ),
        r_seg_sm = labeled_row("sm", &segmented(Size::Sm, false, &["1h", "24h", "7d"], 1)),
    );

    Card {
        slug: "actions",
        group: "Actions",
        title: "Actions",
        body,
        stacked: false,
    }
}

fn feedback_card() -> Card {
    let badges: String = [
        (Tone::Neutral, "Neutral"),
        (Tone::Info, "Info"),
        (Tone::Success, "Success"),
        (Tone::Warn, "Warn"),
        (Tone::Danger, "Danger"),
    ]
    .iter()
    .map(|(tone, label)| badge(*tone, label))
    .collect::<String>();

    let dots: String = [
        (StatusTone::Neutral, "neutral"),
        (StatusTone::Success, "success"),
        (StatusTone::Error, "error"),
        (StatusTone::Running, "running"),
    ]
    .iter()
    .map(|(tone, label)| {
        format!(
            r#"<span style="display:inline-flex; align-items:center; gap:6px; font-size:12px">{dot}{label}</span>"#,
            dot = status_dot(*tone)
        )
    })
    .collect::<String>();

    let toast = |kind: &str, title: &str, detail: &str| {
        format!(
            r#"<div class="toast {kind}"><div class="toast-body"><div class="title">{title}</div><div class="detail">{detail}</div></div><span class="x">{close}</span></div>"#,
            close = close_icon()
        )
    };

    let body = format!(
        "{h_badge}{r_badge}{h_dot}{r_dot}{h_err}{banner}{h_hint}{hint}{h_toast}<div class=\"toasts\">{t1}{t2}{t3}</div>",
        h_badge = heading("Badge — tones"),
        r_badge = labeled_row("tones", &badges),
        h_dot = heading("StatusDot"),
        r_dot = labeled_row("tones", &dots),
        h_err = heading("ErrorBanner"),
        banner =
            r#"<div class="error" role="alert">couldn't reach trawld: connection refused</div>"#,
        h_hint = heading("Loaded — load hints"),
        hint = r#"<div class="load-hint">Loading history…</div><div class="load-hint error">couldn't load history</div>"#,
        h_toast = heading("Toasts"),
        t1 = toast("success", "Saved", "Query \"errors by host\" saved"),
        t2 = toast("error", "Copy failed", "Clipboard unavailable"),
        t3 = toast("info", "Schedule updated", "Next run in 2 hours"),
    );

    Card {
        slug: "feedback",
        group: "Feedback",
        title: "Feedback",
        body,
        stacked: false,
    }
}

fn forms_card() -> Card {
    let toggles = format!("{}{}", toggle(true), toggle(false));
    let seg_full = format!(
        r#"<div style="max-width:340px">{}</div>"#,
        segmented(Size::Default, true, &["CSV", "JSON", "Parquet"], 2)
    );
    let body = format!(
        "{h_field}<div class=\"ds-col\">{f_hint}{f_error}</div>{h_search}{r_search}{h_toggle}{r_toggle}{h_seg}{r_seg}",
        h_field = heading("Field"),
        f_hint = field(
            "name",
            "Query name",
            r#"<input type="text" id="name" value="errors by host"/>"#,
            Some(("field-hint", "Shown in the saved-queries list.")),
        ),
        f_error = field(
            "token",
            "API token",
            r#"<input type="password" id="token" value="hunter2"/>"#,
            Some(("error", "Token was rejected by the server.")),
        ),
        h_search = heading("SearchInput"),
        r_search = labeled_row("filter", &search_input("Filter runs…")),
        h_toggle = heading("Toggle"),
        r_toggle = labeled_row("states", &toggles),
        h_seg = heading("Segmented — full width"),
        r_seg = seg_full,
    );

    Card {
        slug: "forms",
        group: "Forms",
        title: "Forms",
        body,
        stacked: false,
    }
}

fn overlays_card() -> Card {
    let export_modal = modal(
        false,
        "Export results",
        &format!(
            r#"<div class="m-field"><label>Format</label>{seg}</div><div class="m-field"><label>File name</label><input type="text" value="report.csv"/></div>"#,
            seg = segmented(Size::Default, true, &["CSV", "JSON", "Parquet"], 0)
        ),
        &format!(
            "<div></div>{cancel}{confirm}",
            cancel = btn(Variant::Secondary, Size::Default, "Cancel", false),
            confirm = btn(Variant::Primary, Size::Default, "Export", false)
        ),
    );

    let confirm_modal = modal(
        true,
        "Delete saved query",
        r#"<p style="margin:0; font-size:13px; color:var(--ink-2)">Delete "errors by host"? This can't be undone.</p>"#,
        &format!(
            "<div></div>{cancel}{del}",
            cancel = btn(Variant::Secondary, Size::Default, "Cancel", false),
            del = btn(Variant::Danger, Size::Default, "Delete", false)
        ),
    );

    let body = format!(
        "{h_modal}{export_modal}{h_confirm}{confirm_modal}",
        h_modal = heading("Modal"),
        h_confirm = heading("ConfirmModal (narrow, alertdialog)"),
    );

    Card {
        slug: "overlays",
        group: "Overlays",
        title: "Overlays",
        body,
        stacked: false,
    }
}

// ── component emitters and their cards ──────────────────────────────

/// Workspace `<Tabs/>` — `.tabs > div.t[.active]` with optional count
/// chip `.c`, trailing spacer `.sp` (tabs.rs, Workspace arm).
fn tabs_workspace(items: &[(&str, Option<usize>)], active: usize) -> String {
    let mut out = String::from(r#"<div class="tabs">"#);
    for (i, (label, count)) in items.iter().enumerate() {
        let class = if i == active { "t active" } else { "t" };
        let chip = count.map_or(String::new(), |c| format!(r#"<span class="c">{c}</span>"#));
        let _ = write!(
            out,
            r#"<div class="{class}"><span>{label}</span>{chip}</div>"#
        );
    }
    out.push_str(r#"<div class="sp"></div></div>"#);
    out
}

/// Drawer `<Tabs/>` — `.sd-tabs > span.tb[.on]`, spacer, optional
/// trailing `.meta` (tabs.rs, Drawer arm).
fn tabs_drawer(items: &[&str], active: usize, meta: Option<&str>) -> String {
    let mut out = String::from(r#"<div class="sd-tabs">"#);
    for (i, label) in items.iter().enumerate() {
        let class = if i == active { "tb on" } else { "tb" };
        let _ = write!(out, r#"<span class="{class}">{label}</span>"#);
    }
    out.push_str(r#"<span class="sp"></span>"#);
    if let Some(m) = meta {
        let _ = write!(out, r#"<span class="meta">{m}</span>"#);
    }
    out.push_str("</div>");
    out
}

/// `<Pager/>` — `.results-footer` with summary + sm secondary prev/next
/// buttons (pager.rs).
fn pager(summary: &str, can_prev: bool, can_next: bool) -> String {
    let prev = btn(Variant::Secondary, Size::Sm, "← prev", !can_prev);
    let next = btn(Variant::Secondary, Size::Sm, "next →", !can_next);
    format!(
        r#"<footer class="results-footer"><span class="results-summary">{summary}</span><div class="results-pager">{prev}{next}</div></footer>"#
    )
}

/// `<LoadMore/>` — `.load-more` wrapping a secondary Btn or the
/// terminal `.load-more-end` text (`load_more.rs` phase table).
fn load_more(inner: &str) -> String {
    format!(r#"<div class="load-more">{inner}</div>"#)
}

/// `<Sparkline/>` — geometry via fleet-ui's own `spark_path`
/// (sparkline/geometry.rs), assembled exactly as component.rs does.
fn sparkline(data: &[u64], color: &str, w: u32, h: u32) -> String {
    let Some(path) = spark_path(data, f64::from(w), f64::from(h)) else {
        return format!(
            r#"<svg class="sc-spark" width="{w}" height="{h}" viewBox="0 0 {w} {h}"></svg>"#
        );
    };
    format!(
        r#"<svg class="sc-spark" width="{w}" height="{h}" viewBox="0 0 {w} {h}"><polygon points="{fill}" fill="{color}" opacity="0.10"/><polyline points="{line}" fill="none" stroke="{color}" stroke-width="1.25" stroke-linejoin="round"/></svg>"#,
        fill = path.fill,
        line = path.line,
    )
}

/// `<ActionsMenu/>` — `.actions-wrap > .btn-icon` trigger with the
/// panel in static open state (`actions_menu.rs`).
fn actions_menu_open(items: &[(&str, bool)]) -> String {
    let mut menu = String::from(r#"<div class="actions-menu" role="menu">"#);
    for (label, danger) in items {
        let class = if *danger { "item danger" } else { "item" };
        let _ = write!(
            menu,
            r#"<button class="{class}" type="button" role="menuitem">{label}</button>"#
        );
    }
    menu.push_str("</div>");
    format!(
        r#"<div class="actions-wrap"><button class="btn-icon" type="button" aria-haspopup="menu" aria-expanded="true">⋯</button>{menu}</div>"#
    )
}

/// `<When/>` — `.when` span with the RFC 3339 title (time/when.rs).
fn when(label: &str, title: &str) -> String {
    format!(r#"<span class="when" title="{title}">{label}</span>"#)
}

fn navigation_card() -> Card {
    let ws_tabs = tabs_workspace(
        &[
            ("Events", Some(1284)),
            ("Patterns", None),
            ("Sources", Some(12)),
        ],
        0,
    );
    let dr_tabs = tabs_drawer(
        &["Overview", "Fields", "Tail"],
        1,
        Some("3.2k events · 48 MB · 22 fields"),
    );

    let body = format!(
        "{h_ws}{ws_tabs}{h_dr}{dr_tabs}",
        h_ws = heading("Tabs — workspace style"),
        h_dr = heading("Tabs — drawer style (with meta)"),
    );

    Card {
        slug: "navigation",
        group: "Navigation",
        title: "Navigation",
        body,
        stacked: false,
    }
}

fn data_card() -> Card {
    let spark_row = format!(
        "{}{}{}",
        sparkline(
            &[3, 7, 4, 12, 9, 15, 11, 18, 14, 9],
            "var(--accent)",
            120,
            22
        ),
        sparkline(&[2, 2, 3, 2, 8, 14, 6, 3, 2, 2], "var(--green)", 120, 22),
        sparkline(&[0, 0, 0, 0, 0, 0], "var(--red)", 120, 22),
    );
    let whens = format!(
        "{}{}",
        when("5m ago", "2026-07-12T15:40:00+00:00"),
        when("2026-07-12 15:40 UTC", "2026-07-12T15:40:00+00:00"),
    );
    let load_states = format!(
        "{idle}{busy}{end}{empty}",
        idle = load_more(&btn(Variant::Secondary, Size::Default, "load more", false)),
        busy = load_more(&btn(Variant::Secondary, Size::Default, "loading…", true)),
        end = load_more(r#"<span class="load-more-end">end of list</span>"#),
        empty = load_more(r#"<span class="load-more-end">nothing here yet</span>"#),
    );

    let body = format!(
        "{h_pager}{pager}{h_load}{load_states}{h_spark}{r_spark}{h_when}{r_when}{h_menu}<div class=\"ds-dropdown-room\">{menu}</div>",
        h_pager = heading("Pager"),
        pager = pager("1–50 of 213", false, true),
        h_load = heading("LoadMore — idle / busy / end / empty"),
        h_spark = heading("Sparkline"),
        r_spark = labeled_row("series", &spark_row),
        h_when = heading("When — relative / absolute"),
        r_when = labeled_row("modes", &whens),
        h_menu = heading("ActionsMenu (open)"),
        menu = actions_menu_open(&[("Rename", false), ("Duplicate", false), ("Delete", true)]),
    );

    Card {
        slug: "data",
        group: "Data",
        title: "Data",
        body,
        stacked: false,
    }
}

fn drawer_card() -> Card {
    let tabs = tabs_drawer(
        &["Overview", "Fields", "Tail"],
        0,
        Some("3.2k events · 48 MB · 22 fields"),
    );
    let title = format!(
        "{dot}<span>nginx-access</span>",
        dot = status_dot(StatusTone::Success)
    );
    let action = btn(Variant::Secondary, Size::Sm, "Tail", false);
    let drawer_body = r#"<p style="margin:0; font-size:12px; color:var(--ink-2)">Drawer body — app-owned pane content renders here.</p>"#;

    let body = format!(
        r#"{h}<div class="sd-scrim"><aside class="sd-drawer" role="dialog"><div class="sd-hd"><div class="sd-ttl">{title}</div><div class="sd-actions">{action}<span class="sd-x" title="Close (Esc)">{close}</span></div></div>{tabs}<div class="sd-body">{drawer_body}</div></aside></div>"#,
        h = heading("Drawer (open, drawer tabs + meta)"),
        close = close_icon(),
    );

    Card {
        slug: "drawer",
        group: "Overlays",
        title: "Drawer",
        body,
        stacked: false,
    }
}

fn reason_modal_card() -> Card {
    let modal_body = r#"<p style="margin:0; font-size:13px; color:var(--ink-2)">Invalidate this run? Downstream reports will be regenerated.</p><div class="m-field"><label>Reason</label><textarea class="reason-input" placeholder="Why is this run being invalidated?"></textarea></div>"#;
    let footer = format!(
        "<div></div>{cancel}{confirm}",
        cancel = btn(Variant::Secondary, Size::Default, "Cancel", false),
        confirm = btn(Variant::Danger, Size::Default, "Invalidate", true),
    );
    let body = format!(
        "{h}{m}",
        h = heading("ConfirmWithReasonModal (confirm disabled until reason)"),
        m = modal(true, "Invalidate run", modal_body, &footer),
    );

    Card {
        slug: "reason-modal",
        group: "Overlays",
        title: "Reason modal",
        body,
        stacked: false,
    }
}

fn login_card() -> Card {
    let submit = btn_full(Variant::Form, Size::Default, true, "Sign in", false);
    let body = format!(
        r#"{h}<div class="login-shell"><form class="login-card"><h1><span>traw</span><span class="accent">l</span></h1><p class="subtitle">sign in with your API key</p><label class="field"><span>API key</span><input type="password" autocomplete="off" spellcheck="false"/></label>{submit}</form></div>"#,
        h = heading("Login"),
    );

    Card {
        slug: "login",
        group: "Chrome",
        title: "Login",
        body,
        stacked: false,
    }
}

fn chrome_card() -> Card {
    let topbar = format!(
        r#"<header class="topbar"><button type="button" class="nav-toggle" style="display:inline-flex">{menu}</button><h2 class="crumb">Search</h2><div class="sp"></div><button type="button" class="jump">{search}<span class="gh">Go to…</span><span class="kbd">⌘K</span></button><div class="user-wrap"><button type="button" class="user"><span class="avatar">JB</span><span class="who">jakub</span>{chevron}</button></div></header>"#,
        menu = icon_svg(16, r#"<g><path d="M2 4h12M2 8h12M2 12h12"/></g>"#),
        search = search_icon(),
        chevron = icon_svg(10, r#"<g><path d="m4 6 4 4 4-4"/></g>"#),
    );

    let item = |icon: &str, label: &str, active: bool, badge: Option<u64>| {
        let class = if active { "it active" } else { "it" };
        let chip = badge.map_or(String::new(), |n| {
            format!(r#"<span class="badge">{n}</span>"#)
        });
        format!(
            r#"<a class="{class}" title="{label}">{icon}<span class="lb">{label}</span>{chip}</a>"#
        )
    };
    let sidebar = format!(
        r#"<nav class="rail" style="height:320px"><div class="brand"><span>traw</span><span class="accent">l</span></div><div class="grp">{search}{history}</div><div class="grp" role="group" aria-label="Operations"><span class="grp-lb">Operations</span>{alerts}</div><div class="bot"><a class="it" title="Help"><span class="lb">Help</span></a><button type="button" class="it collapse">{panel}<span class="lb">Collapse</span></button></div></nav>"#,
        search = item(
            &icon_svg(
                18,
                r#"<g><circle cx="7" cy="7" r="4.5"/><path d="m10.5 10.5 3 3"/></g>"#
            ),
            "Search",
            true,
            None
        ),
        history = item(
            &icon_svg(
                18,
                r#"<g><circle cx="8" cy="8" r="6"/><path d="M8 5v3l2 1.5"/></g>"#
            ),
            "History",
            false,
            None
        ),
        alerts = item(
            &icon_svg(
                18,
                r#"<g><path d="M8 2 14 13H2z"/><path d="M8 6.5v3M8 11.5v.01" stroke-linecap="round"/></g>"#
            ),
            "Alerts",
            false,
            Some(7)
        ),
        panel = icon_svg(
            18,
            r#"<g><rect x="1" y="2" width="14" height="12" rx="1"/><path d="M5.5 2v12"/></g>"#
        ),
    );

    let user_menu = r#"<div class="user-wrap" style="display:inline-block"><div class="user-menu" style="position:static; animation:none"><div class="hdr"><div class="name">jakub</div><div class="mail">admin</div></div><div class="item"><span>Switch to dark theme</span></div><div class="sep"></div><div class="item danger"><span>Sign Out</span></div></div></div>"#;

    let body = format!(
        "{h_top}{topbar}{h_side}{sidebar}{h_menu}{user_menu}",
        h_top = heading("Command bar"),
        h_side = heading("Sidebar"),
        h_menu = heading("User menu (open)"),
    );

    Card {
        slug: "chrome",
        group: "Chrome",
        title: "App chrome",
        body,
        stacked: true,
    }
}
